// Firestore Collections and Document Structure Guide

/*
FIRESTORE COLLECTION: 'stopCardReports'

Document Structure:
{
  // Document ID: Auto-generated by Firestore
  
  // Basic Info
  reportId: "STOP_1234567890_abc123def",
  timestamp: serverTimestamp(),
  submittedAt: "2025-09-26T10:30:00Z",
  
  // User Information
  userInfo: {
    email: "john.doe@company.com",
    displayName: "John Doe",
    companyId: "31234",
    uid: "firebase_user_uid"
  },
  
  // Site Information
  siteInfo: {
    site: "Manufacturing Plant A",
    area: "Assembly Line 2", 
    date: "2025-09-26",
    shift: "A"
  },
  
  // Observation Data
  observationData: {
    durationMinutes: 45,
    peopleConducted: 5,
    peopleObserved: 12
  },
  
  // Safety Acts
  safetyActs: {
    safeActsCount: 3,
    safeActsList: [
      "Proper use of safety equipment",
      "Following lockout procedures", 
      "Maintaining clean workspace"
    ],
    unsafeActsCount: 1,
    unsafeActsList: [
      "Not wearing safety glasses"
    ]
  },
  
  // Completion Rates
  completionRates: {
    actionsCompletion: 85,
    conditionsCompletion: 92
  },
  
  // Detailed Assessment Data
  assessmentData: {
    actions: [
      {
        category: "Reactions of People",
        questions: [
          {
            question: "Adjusting Personal Protective Equipment",
            status: true
          },
          // ... more questions
        ]
      },
      // ... more categories
    ],
    conditions: [
      {
        category: "Tools and Equipment",
        questions: [
          {
            question: "Right for the job",
            status: true
          },
          // ... more questions
        ]
      },
      // ... more categories
    ]
  },
  
  // User Feedback
  feedback: {
    suggestions: "Consider adding more safety signage in the work area"
  },
  
  // Metadata
  metadata: {
    appVersion: "1.0.0",
    platform: "mobile",
    submissionMethod: "stopcard_form"
  }
}

FIRESTORE QUERIES EXAMPLES:

// Get all reports for a specific user
const userReports = await getDocs(
  query(
    collection(db, 'stopCardReports'),
    where('userInfo.companyId', '==', '31234'),
    orderBy('timestamp', 'desc')
  )
);

// Get reports for a specific date range
const dateRangeReports = await getDocs(
  query(
    collection(db, 'stopCardReports'),
    where('siteInfo.date', '>=', '2025-09-01'),
    where('siteInfo.date', '<=', '2025-09-30'),
    orderBy('siteInfo.date', 'desc')
  )
);

// Get reports for a specific site
const siteReports = await getDocs(
  query(
    collection(db, 'stopCardReports'),
    where('siteInfo.site', '==', 'Manufacturing Plant A'),
    orderBy('timestamp', 'desc'),
    limit(50)
  )
);

// Get reports with unsafe acts
const unsafeActsReports = await getDocs(
  query(
    collection(db, 'stopCardReports'),
    where('safetyActs.unsafeActsCount', '>', 0),
    orderBy('safetyActs.unsafeActsCount', 'desc')
  )
);

BENEFITS:
- Real-time data synchronization
- Rich querying capabilities
- Automatic indexing
- Offline support
- Data validation
- Scalable architecture
- Analytics integration
- Security rules support

*/

export default {
  collectionName: 'stopCardReports',
  structure: 'See comments above for complete document structure'
};